<!-- if we're logged in, provide a quick rundown of lists we're subscribed to. -->
<h1>My Lists</h1>
<p>
The following table contains all lists you're subscribed to.
<p>
<table>
<%foreach var="$user.Subscriptions" val="subscription"%>
<tr>
<td>
  <%action_link controller="/listinfo" args="$subscription.List.name"%><%$subscription.List.name%></a>
</td>
<td>
<%autoformat var="$subscription.List.title"%>
</td>
</tr>
<%end%>
</table>
<p/>

