<h1>SpeedyDelivery 1.0</h1>

&copy; 2008-2011 Bill Welliver &lt;hww3 at welliver dot org&gt;
<p/>
SpeedyDelivery is software for managing electronic mail discussion and e-newsletter lists. 
SpeedyDelivery is integrated with the web, making it easy for users to manage their accounts and for list owners to administer their lists. SpeedyDelivery supports built-in archiving, automatic bounce processing, digest delivery and more.
<p/>
<ul>
<li><a href="http://hww3.riverweb.com/space/pike/SpeedyDelivery">SpeedyDelivery Home Page</a>
<li><a href="http://hg.welliver.org/SpeedyDelivery">Mercurial Repository</a>
</ul>