<h1>Account information for <%$user.email%>.</h1>
<form action="<%action_url action="update"%>" method="post">
<b>User Info</b>
<br/>
You can update your real name but not your email address. To change the email address your mail gets delivered to, you must resubscribe to lists using 
that new 
email address.
<p>
Real Name: <input type="string" name="name" value="<%$user.name%>">
<p>
<input type="hidden" name="action" value="update"/>
<input type="submit" value="Update Account Info"/>
</form>
<p>
<form action="<%action_url action="update"%>" method="post">
<b>Reset Password</b>
<br/>
Password: <input type="password" name="reset_1"/>
<br/>
Retype Password: <input type="password" name="reset_2"/>
<p>
<input type="hidden" name="action" value="password"/>
<input type="submit" value="Change Password"/>
</form>

