<h1>Account information for <%$user.email%>.</h1>

<form>
<b>User Info</b>
<br/>
You can update your real name but not your email address. To change the email address your mail gets delivered to, you must resubscribe to lists using 
that new 
email address.
<p>
Real Name: <input type="string" name="name" value="<%$user.name%>">
<p>
<input type="hidden" name="action" value="update"/>
<input type="submit" value="Update Account Info"/>
</form>
<p>
<form>
<b>Reset Password</b>
<br/>
Password: <input type="password" name="reset_password"/>
<br/>
Retype Password: <input type="password" name="reset_password2"/>
<p>
<input type="hidden" name="action" value="password"/>
<input type="submit" value="Change Password"/>
</form>

