// auto-generated by Fins.AdminTools.ModelBuilder for table confirmations.

inherit Fins.Model.DataObject;

void post_define(object context)
{
// Add any post configuration logic here

  add_field(context, Fins.Model.MetaDataField("_options", "options"));
  set_alternate_key("confid");

}

