// auto-generated by Fins.AdminTools.ModelBuilder for table held_messages.

inherit Fins.Model.DataObject;

void post_define()
{
// Add any post configuration logic here
  set_alternate_key("holdid");

// set_alternate_key("myalternatekey");

}

