// auto-generated by Fins.AdminTools.ModelBuilder for table subscribers.

inherit Fins.Model.DataObject;

void post_define(object context)
{
// Add any post configuration logic here
  has_many_to_many(context, "lists_owners", "List", "list_owner", "owned_list");
}

void validate(mapping changes, object errors, object i)
{
  if(changes->email)
  {
    object r;
    catch(r = Mail.MailAddress(changes->email));
    if(!r)
      errors->add("email", "must be a valid address.");
  }
}  

