// auto-generated by Fins.AdminTools.ModelBuilder.

inherit Fins.Model.DirectAccessInstance;
object repository = Fins.Model;
string type_name = "Confirmation";

void new_from_request(SpeedyDelivery.Request r)
{
  this["list"] = r->list["name"];
  this["email"] = sprintf("%O", r->sender);
  this["confid"] = gen_confid();  
  this["conftype"] = r->functionname;
  save();
}

string gen_confid()
{
  return sprintf("%{%01x%}", 
    (array)Crypto.Random.random_string(25))[0..24];
}
