<html>
<head>
  <title>SpeedyDelivery: Account information for <%$user.email%></title>
</head>
</html>
<body>
<div><font color="red"><i><%flash%></i></font></div>
<div class="userbar">
<%if data->user %>
Logged in as <%$user.email%>. <%action_link controller="/auth" action="logout" return_to="$request.not_query"%>Logout</a> / 
<%action_link controller="/account" %>Edit</a> your user info.
<p/>
<% else %>
You are not currently logged in. <%action_link controller="/auth" action="login" return_to="$request.not_query"%>Login</a> to access your personal
settings.
<p/>
<% endif %>

<%yield%>
<p>
<div class="footer">
<%action_link controller="/" %>SpeedyDelivery Home</a>
</div>
</body>
</html>
