<b>About <%$list.name%></b>
<p>
<%autoformat var="$list.description"%>
</p>
<hr/>
<b>Using <%$list.name%> (<%$list.title%>)</b>
<p>
To post a message to all the list members, send email to 
<a 
href="mailto:<%human_email var="$list._addresses.__default"%>"><%human_email var="$list._addresses.__default"%></a>.

<%if data["list"]["_options"]["reject_non_subscribers"] == 1 %>
<i>Note: this list's policy prohibits non-subscribers from posting.</i>
<%endif%>
<p/>
<p>
You can subscribe to the list, or change your existing subscription, in 
the sections below. 
</p>
<hr/>

<%if data->user && data->subscription %>
<b>Archives</b>
<p>
<%action_link controller="/archive" action="list" args="$list.name"%>View</a> this list's archives.
</p>
<hr/>
<b>Delivery Settings</b>
<p>
You are subscribed to this list. You may modify the delivery settings for your
subscription here.
</p>
<form action="<%action_url controller="/commands" action="setmode" args="$list.name"%>" method="post">
Delivery mode:
<input type="radio" name="mode" value="M" <%if data->subscription["mode"] == "M"%>checked="1"<%endif%>/>
Individual Messages
<input type="radio" name="mode" value="D" <%if data->subscription["mode"] == "D"%>checked="1"<%endif%>/>
Digest
<input type="radio" name="mode" value="S" <%if data->subscription["mode"] == "S"%>checked="1"<%endif%>/>
No Mails
<p>
<input type="submit" name="submit" value="Submit"/>
</form>
<hr/>
<%else%>
<b>Archives</b>
<p>
You must be subscribed to this list in order to view the list archives.
</p>
<hr/>
<b>Subscribing to <%$list.name%></b>
<p>
 Subscribe to <%$list.name%> by filling out the following form.
<p/>
<p>
You will be sent email requesting confirmation, to prevent others 
from gratuitously subscribing you.
</p>
<form action="<%action_url controller="/commands" action="subscribe" args="$list.name"%>" method="post">
<table>
<tr>
<td>
Email: 
</td>
<td><input type="string" name="email"/>
</td>
</tr>
<tr>
<td>Your name (optional):</td>
<td><input type="string" name="name"/></td>
</tr>
<tr>
<td>Digest mode:</td>
<td><input type="radio" name="digest" value="1"/> Yes 
<input type="radio" name="digest" value="0" checked="1"/> No</td>
</tr>
</table>
<input type="submit" name="submit" value="Submit"/>
</form>

<hr/>

<%endif%>
<b>Unsubscribing from <%$list.name%></b>
<p>
 Unsubscribe from <%$list.name%> by filling out the following form.
</p>
<p>
You will be sent email requesting confirmation, to prevent others 
from gratuitously unsubscribing you.
</p>
<form action="<%action_url controller="/commands" action="unsubscribe" args="$list.name"%>" method="post">
<table>
<tr>
<td>
Email: 
</td>
<td><input type="string" name="email"/>
</td>
</tr>
</table>
<input type="submit" name="submit" value="Submit"/>
</form>

<% if data->user && data->list->is_owner(data->user) %>
<hr/>
<b>List Administration</b>
<p>
 You're a list owner. Access the list's administration page <%action_link controller="/listadmin" action="display" args="$list.name"%>here</a>.
</p>
<%endif %>
