<b>Administration for <%$list.name%></b>
<hr/>
<b>Subscribers</b>
<br/>
<%action_link action="displaysubscriptions" args="$list.name"%>Manage Subscribers</a><br>
<%action_link action="listusers" args="$list.name"%>Export Subscriber List</a>
<hr/>
<b>Pending Messages</b>
<br/>
<%action_link action="displayholds" args="$list.name"%>Manage Pending Messages</a><br>
<br/>
<hr/>
<b>List Settings</b>
<br/>
<%action_link action="displaysettings" args="$list.name"%>List Settings</a><br>

