<html>
<head>
	<title>Set up Speedy Delivery</title>
</head>
<body>
	<h1>Welcome to Speedy Delivery!</h1>
	
<font color="red"><i><%flash%></i></font>
<p>
<%action_form action="setup_admin"%>
Before SpeedyDelivery can start handling your mailing lists, there are a few settings that
need to be configured. On the next few pages, you'll provide the values for these settings.
<p>
To get started, click on the button below.
<p>
		<input type="submit" name="action" value="Get Started"/>
	
	</form>
	
	</body>
</html>