<b>Create new list</b>
<hr/>
<%action_form method="post" action="do_new"%>
<b>Name</b>, the short name of the list, used as the username part of the address (that is, before the @ sign). Must start with a letter and may contain alpha numeric characters only.<br/>
<input type="text" size="40" name="name" value="<%$name%>">
<p/>
<b>List Domain</b>, (optional) the domain that will be hosting this list. Used as the hostname part of the address (that is, after the @ sign). Note that SpeedyDelivery and your mail system must be properly configured to receive mail at this host/domain.<br/>
<input type="text" size="40" name="return_host" value="<%$return_host%>">
<p/>
<b>Title</b>, a short description of the list, typically used in descriptive material about this list<br/>
<input type="text" size="40" name="title" value="<%$title%>">
<p/>
<b>Description</b>, a more in depth description of your new list.<br/>
<textarea name="description"><%$description%></textarea>
<p/>
<b>Owner</b>, the user who will oversee day to day operation of the list. Must be a real mail address.<br/>
<input type="text" size="40" name="owner_address" value="<%$owner_address%>">
<p/>
<input type="submit" value="Create List">
</form>


