<% if data->user %>
<!-- if we're logged in, provide a quick rundown of lists we're subscribed to. -->
<b>My Lists</b>
<table>
<%foreach var="$user.Subscriptions" val="subscription"%>
<tr>
<td>
  <%action_link controller="/listinfo" args="$subscription.List.name"%><%$subscription.List.name%></a>
</td>
<td>
<%autoformat var="$subscription.List.description"%>
</td>
</tr>
<%end%>
</table>
<p/>
<hr/>
<% else %>
<% endif %>
<b>Lists available at this server</b>
<hr/>
<table>
<%foreach var="$lists" val="list"%>
<tr>
<td>
  <%action_link controller="/listinfo" args="$list.name"%><%$list.name%></a>
</td>
<td>
<%autoformat var="$list.description"%>
</td>
</tr>
<%end %>
</table>

