// auto-generated by Fins.AdminTools.ModelBuilder for table confirmations.

inherit Fins.Model.DataObject;

void post_define()
{
// Add any post configuration logic here

  set_alternate_key("confid");

}

