// auto-generated by Fins.AdminTools.ModelBuilder for table lists.

inherit Fins.Model.DataObject;

void post_define()
{
// Add any post configuration logic here
  add_field(Fins.Model.MetaDataField("_options", "options"));
  set_alternate_key("name");
}

