// auto-generated by Fins.AdminTools.ModelBuilder for table lists.

inherit Fins.Model.DataObject;

void post_define()
{
// Add any post configuration logic here

// set_alternate_key("myalternatekey");

}

