// auto-generated by Fins.AdminTools.ModelBuilder for table subscribers.

inherit Fins.Model.DataObject;

void post_define()
{
// Add any post configuration logic here

 set_alternate_key("email");
}

void validate(mapping changes, object errors, object i)
{
  if(changes->email)
  {
    object r;
    catch(r = Mail.MailAddress(changes->email));
    if(!r)
      errors->add("email", "must be a valid address.");
  }
}  

