<title>Password Reset</title>
   <h3>Password Reset</h3>
<p/>
Enter your email and password in the form below, along with your desired new password. Then, click on "Reset." Your account password will be reset.
   <p/>
<%flash%>
<p/>
<form action="<%action_url action="changepassword"%>" method="post">
<input type="hidden" name="return_to" value="<%$return_to%>"/>
<table>
<tr>
<td>Email:</td> <td><input type="string" name="username" value="<%$username%>"/><br/></td>
</tr>
<td>
Current Password:</td> <td><input type="password" name="password" value="<%$password%>"/><br/></td>
</tr>
<tr><td>&nbsp;</td><td></td>
</tr>
<tr>
<td>
New Password:</td> <td><input type="password" name="newpassword"/><br/></td>
</tr>
<tr>
<td>Confirm New Password: </td> <td><input type="password" name="newpassword2"/><br/></td>
</tr>
<tr><td>&nbsp;</td><td></td>
</tr>
<tr>
<td>
<input type="submit" name="action" value="Reset"/>
</td><td></td></tr>
</table>
</form>

